development:
  access_key_id: "XXXX"
  secret_access_key: "YYYY"
test:
  access_key_id: "XXXX"
  secret_access_key: "YYYY"
production:
  access_key_id: "XXXX"
  secret_access_key: "YYYY"
#TODO add correct security credentials
